---

sublime_apt_repo:
  file: sublime
  repo: "deb https://download.sublimetext.com/ apt/{{ sublime_repo_channel }}/"

# ID: curl https://download.sublimetext.com/sublimehq-pub.gpg | gpg --list-packets
sublime_apt_key:
  url: https://download.sublimetext.com/sublimehq-pub.gpg
  id: ADAE6AD28A8F901A

sublime_config_path: "{{ lookup('env','HOME') }}/.config"
sublime_package_path: "{{ sublime_config_path }}/sublime-text-3/Installed Packages"
