---

- name: ensure telegram symlink is removed
  file:
    state: absent
    path: "{{ telegram_bin_path }}/Telegram"
  become: yes

- name: ensure telegram is removed
  file:
    state: absent
    path: "{{ telegram_opt_path }}/Telegram"
  become: yes
