---

- name: ensure diff-highlight is downloaded
  get_url:
    url: https://raw.githubusercontent.com/K-Phoen/Config/master/bin/diff-highlight
    dest: "{{ diff_highlight_path }}"
    mode: 0755
    force: yes
    timeout: 30
  register: task_result
  until: task_result | succeeded
  retries: 10
  delay: 5
  become: yes
