---

- name: ensure linux timemachine requirements are installed
  include_role:
    name: apt-meta
  vars:
    apt_packages:
      - "{{ timemachine_shared_packages }}"

- name: ensure linux timemachine is downloaded
  get_url:
    url: https://raw.githubusercontent.com/cytopia/linux-timemachine/master/timemachine
    dest: "{{ timemachine_path }}"
    mode: 0755
    force: yes
    timeout: 30
  register: task_result
  until: task_result | succeeded
  retries: 10
  delay: 5
  become: yes
