---

- name: ensure xbacklight is removed
  file:
    state: absent
    path: "{{ xbacklight_path }}"
  become: yes

- name: ensure udev rules are removed
  file:
    state: absent
    path: "{{ xbacklight_udev_rules_dir }}/90-backlight.rules"
  become: yes
