---

- name: ensure required packages are installed
  apt:
    state: latest
    name: "{{ item }}"
    update_cache: yes
    install_recommends: no
  become: yes
  with_items: "{{ apt_repo_packages }}"

- name: ensure default sources.list is removed
  file:
    state: absent
    path: /etc/apt/sources.list
  become: yes
  notify: update apt repository cache

- name: ensure apt keys are managed
  apt_key:
    state: "{{ apt_repo_state }}"
    id: "{{ item.id | default(omit) }}"
    file: "{{ item.file | default(omit) }}"
    keyserver: "{{ item.keyserver | default(omit) }}"
    url: "{{ item.url | default(omit) }}"
    validate_certs: yes
  become: yes
  with_items:
    - "{{ apt_repo_keys }}"
  notify: update apt repository cache

- name: ensure apt repositories are managed
  apt_repository:
    state: "{{ apt_repo_state }}"
    repo: "{{ item.repo }}"
    filename: "{{ item.file }}"
    validate_certs: yes
    update_cache: yes
  become: yes
  with_items:
    - "{{ apt_repo_repositories }}"
  notify: update apt repository cache

# Make sure the handler runs now and not at the end of the playbook
- meta: flush_handlers
