---

- name: ensure virtualbox is removed
  include_role:
    name: apt-meta
  vars:
    apt_state: absent
    apt_packages:
      - "{{ virtualbox_package_name }}"

- name: ensure virtualbox repo is removed
  include_role:
    name: apt-repo-meta
  vars:
    apt_repo_state: absent
    apt_repo_keys:
      - "{{ virtualbox_apt_key }}"
    apt_repo_repositories:
      - "{{ virtualbox_apt_repo }}"
