---

# 'install', 'remove' or 'ignore'
sxiv: 'ignore'

sxiv_default_image_viewer: yes

# Mime types sxiv should be the default image editor
sxiv_default_mime_types:
  - image/bmp
  - image/gif
  - image/jpeg
  - image/jpg
  - image/png
  - image/tiff
  - image/x-bmp
  - image/x-portable-anymap
  - image/x-portable-bitmap
  - image/x-portable-graymap
  - image/x-tga
  - image/x-xpixmap

# Mime types sxiv should be able to handle
sxiv_mime_types:
  - image/bmp
  - image/gif
  - image/jpeg
  - image/jpg
  - image/png
  - image/tiff
  - image/x-bmp
  - image/x-portable-anymap
  - image/x-portable-bitmap
  - image/x-portable-graymap
  - image/x-tga
  - image/x-xpixmap
