---

- name: ensure requirements are installed
  include_role:
    name: apt-meta
  vars:
    apt_packages:
      - "{{ i3_utils_bin_shared_packages }}"

- name: ensure i3-utils-bin tools are downloaded
  get_url:
    url: "https://raw.githubusercontent.com/cytopia/i3-utils-bin/master/bin/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: 0755
    force: yes
    timeout: 30
  register: task_result
  until: task_result | succeeded
  retries: 10
  delay: 5
  become: yes
  with_items:
    - "{{ i3_utils_bin_tools }}"

- name: ensure applications folder exist
  file:
    state: directory
    path: /usr/share/applications
    mode: 0755

- name: ensure ximage desktop file is present
  get_url:
    url: https://raw.githubusercontent.com/cytopia/i3-utils-bin/master/applications/ximage.desktop
    dest: /usr/share/applications/ximage.desktop
    mode: 0644
    force: yes
    timeout: 30
  register: task_result
  until: task_result | succeeded
  retries: 10
  delay: 5
  become: yes
