---

- name: ensure skype repo is present
  include_role:
    name: apt-repo-meta
  vars:
    apt_repo_keys:
      - "{{ skype_apt_key }}"
    apt_repo_repositories:
      - "{{ skype_apt_repo }}"

- name: ensure skype is installed
  include_role:
    name: apt-meta
  vars:
    apt_packages:
      - skypeforlinux
