---

- name: ensure skype is removed
  include_role:
    name: apt-meta
  vars:
    apt_state: absent
    apt_packages:
      - skypeforlinux

- name: ensure skype repo is removed
  include_role:
    name: apt-repo-meta
  vars:
    apt_repo_state: absent
    apt_repo_keys:
      - "{{ skype_apt_key }}"
    apt_repo_repositories:
      - "{{ skype_apt_repo }}"
