---
# ---------------------------------------------------------------------------------------------------------------------
# PRIMARY SYSCTL KEY VALUES FOR (HIGH) PERFORMANCE SYSTEMS
# ---------------------------------------------------------------------------------------------------------------------

# kernel
randomize_va_space: 2
kptr_restrict: 1
dmesg_restrict: 1
ptrace_scope: 2
sched_migration_cost_ns: 5000000

# vm/swap
mmap_min_addr: 65536
swappiness: 10
dirty_ratio: 60
dirty_background_ratio: 2

# fs
file_max: 2097152

# net.ipv4
tcp_syncookies: 1
tcp_max_syn_backlog: 2048
tcp_fin_timeout: 15
tcp_max_tw_buckets: 1440000
tcp_tw_recycle: 1
tcp_tw_reuse: 1
tcp_keepalive_time: 300
tcp_keepalive_probes: 5
tcp_keepalive_intvl: 15
tcp_synack_retries: 3
tcp_syn_retries: 3
tcp_max_orphans: 65535
tcp_rfc1337: 1
tcp_mem: "786432 1048576 26777216"
tcp_wmem: "8192 65536 33554432"
tcp_rmem: "8192 87380 33554432"
udp_mem: "65536 131072 262144"
udp_wmem_min: 16384
udp_rmem_min: 16384
ip_local_port_range: "2000 65535"

# net.core
rmem_default: 31457280
rmem_max: 33554432
wmem_default: 31457280
wmem_max: 33554432
somaxconn: 65536
netdev_max_backlog: 65536
optmem_max: 25165824

# net.filter
nf_conntrack_tcp_loose: 0

# ---------------------------------------------------------------------------------------------------------------------
# OPTIONAL CONFIG VALUES
#
# - activate 'force_sysctl_reload' in prod-environment to re-evaluate written sysctl parameter settings directly
# ---------------------------------------------------------------------------------------------------------------------

# force_sysctl_reload: yes
