---

- name: ensure docker repo is present
  include_role:
    name: apt-repo-meta
  vars:
    apt_repo_keys:
      - "{{ docker_apt_key }}"
    apt_repo_repositories:
      - "{{ docker_apt_repo }}"

- name: ensure docker is installed
  include_role:
    name: apt-meta
  vars:
    apt_packages:
      - "{{ docker_package_name }}"

- name: set username
  command: whoami
  register: docker_username
  check_mode: no
  changed_when: False

- name: ensure user is added to docker group
  user:
    name: "{{ docker_username.stdout }}"
    groups: docker
    append: yes
    update_password: on_create
  become: yes
