---

- name: ensure thunar custom actions are removed
  file:
    state: absent
    path: "{{ thunar_custom_actions_bin_path }}/{{ item }}"
  become: yes
  with_items:
    - "{{ thunar_custom_actions_tools }}"
