---

- name: ensure hipchat requirements are installed
  include_role:
    name: apt-meta
  vars:
    apt_packages:
      - "{{ hipchat_shared_packages }}"

- name: ensure hipchat repo is present
  include_role:
    name: apt-repo-meta
  vars:
    apt_repo_keys:
      - "{{ hipchat_apt_key }}"
    apt_repo_repositories:
      - "{{ hipchat_apt_repo }}"

- name: ensure hipchat is installed
  include_role:
    name: apt-meta
  vars:
    apt_packages:
      - "{{ hipchat_package_name }}"
