---

- name: assert that hipchat repository distribution is set correctly
  assert:
    that:
      - hipchat_repo_dist == 'wheezy' or hipchat_repo_dist == 'jessie' or hipchat_repo_dist == 'stretch' or hipchat_repo_dist == 'buster'
    msg: hipchat_repo_dist must be 'wheezy', 'jessie', 'stretch' or 'buster'

- include_tasks: install.yml
  when: hipchat == 'install'

- include_tasks: uninstall.yml
  when: hipchat == 'remove'
