---

- name: ensure hipchat is removed
  include_role:
    name: apt-meta
  vars:
    apt_state: absent
    apt_packages:
      - "{{ hipchat_package_name }}"

- name: ensure hipchat repo is removed
  include_role:
    name: apt-repo-meta
  vars:
    apt_repo_state: absent
    apt_repo_keys:
      - "{{ hipchat_apt_key }}"
    apt_repo_repositories:
      - "{{ hipchat_apt_repo }}"
